#!/usr/bin/env python3
"""Bundle repeated page-family scripts into generated assets."""
from __future__ import annotations

from pathlib import Path
import re
import sys

try:
    import rjsmin
    _HAS_RJSMIN = True
except ImportError:
    _HAS_RJSMIN = False

ROOT = Path(__file__).resolve().parents[1]
JS_DIR = ROOT / "js"

BUNDLES = [
    {
        "output": "module-pages.bundle.js",
        "output_min": "module-pages.bundle.min.js",
        "sources": [
            "module-quiz.js",
            "module-scenarios.js",
        ],
        "description": "module page bundle",
    },
]


def strip_leading_banner(source: str) -> str:
    return re.sub(r"^\s*/\*.*?\*/\s*", "", source, count=1, flags=re.DOTALL)


def trim_blank_runs(source: str) -> str:
    lines = [line.rstrip() for line in source.splitlines()]
    collapsed: list[str] = []
    previous_blank = False
    for line in lines:
        is_blank = line == ""
        if is_blank and previous_blank:
            continue
        collapsed.append(line)
        previous_blank = is_blank
    return "\n".join(collapsed).strip() + "\n"


def build_bundle(bundle: dict[str, object]) -> None:
    parts: list[str] = []
    sources = bundle["sources"]
    assert isinstance(sources, list)
    for rel_path in sources:
        path = JS_DIR / str(rel_path)
        if not path.exists():
            raise SystemExit(f"Missing JS source file: {path}")
        body = trim_blank_runs(strip_leading_banner(path.read_text(encoding="utf-8")))
        parts.append(f"/* Source: js/{rel_path} */\n{body}")

    output_path = JS_DIR / str(bundle["output"])
    output_min_path = JS_DIR / str(bundle["output_min"])
    description = str(bundle["description"])
    output = (
        f"/* Auto-generated by scripts/build_page_group_bundles.py ({description}). */\n"
        f"/* Do not edit {output_path.name} directly; edit the source files and rebuild. */\n\n"
        + ";\n".join(parts).rstrip()
        + "\n"
    )
    output_path.write_text(output, encoding="utf-8")
    size = output_path.stat().st_size
    print(f"Built {output_path.relative_to(ROOT)} from {len(sources)} source file(s), {size} bytes.")

    if _HAS_RJSMIN:
        minified = rjsmin.jsmin(output)
        output_min_path.write_text(minified, encoding="utf-8")
        min_size = output_min_path.stat().st_size
        savings = round((1 - min_size / size) * 100) if size else 0
        print(f"Minified {output_min_path.relative_to(ROOT)}: {min_size} bytes ({savings}% smaller).")
    else:
        print("rjsmin not installed — skipping minification. Run: pip install rjsmin")


def main() -> int:
    for bundle in BUNDLES:
        build_bundle(bundle)
    return 0


if __name__ == "__main__":
    sys.exit(main())
