#!/usr/bin/env python3
"""Concatenate ordered CSS source partials into css/styles.css."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "css" / "src"
MANIFEST = SRC_DIR / "manifest.txt"
OUTPUT = ROOT / "css" / "styles.css"


def read_manifest() -> list[str]:
    if not MANIFEST.exists():
        raise SystemExit(f"Missing manifest: {MANIFEST}")
    items: list[str] = []
    for raw_line in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        items.append(line)
    if not items:
        raise SystemExit("CSS manifest is empty.")
    return items


def build() -> int:
    parts: list[str] = []
    for rel_path in read_manifest():
        css_path = SRC_DIR / rel_path
        if not css_path.exists():
            raise SystemExit(f"Missing CSS source file: {css_path}")
        body = css_path.read_text(encoding="utf-8").rstrip()
        parts.append(f"/* Source: css/src/{rel_path} */\n{body}\n")

    output = (
        "/* Auto-generated by scripts/build_css.py. */\n"
        "/* Do not edit css/styles.css directly; edit css/src/* and rebuild. */\n\n"
        + "\n".join(parts).rstrip()
        + "\n"
    )
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Built {OUTPUT.relative_to(ROOT)} from {len(parts)} source file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(build())
