#!/usr/bin/env python3
"""Bundle the shared frontend main modules into one generated asset."""
from __future__ import annotations

from pathlib import Path
import re
import sys

try:
    import rjsmin
    _HAS_RJSMIN = True
except ImportError:
    _HAS_RJSMIN = False

ROOT = Path(__file__).resolve().parents[1]
JS_DIR = ROOT / "js"
OUTPUT = JS_DIR / "main.bundle.js"
OUTPUT_MIN = JS_DIR / "main.bundle.min.js"
SOURCES = [
    "main-analytics.js",
    "main-learning-loop.js",
    "main-ui.js",
]


def strip_leading_banner(source: str) -> str:
    return re.sub(r"^\s*/\*.*?\*/\s*", "", source, count=1, flags=re.DOTALL)


def trim_blank_runs(source: str) -> str:
    lines = [line.rstrip() for line in source.splitlines()]
    collapsed: list[str] = []
    previous_blank = False
    for line in lines:
        is_blank = line == ""
        if is_blank and previous_blank:
          continue
        collapsed.append(line)
        previous_blank = is_blank
    return "\n".join(collapsed).strip() + "\n"


def build() -> int:
    parts: list[str] = []
    for rel_path in SOURCES:
        path = JS_DIR / rel_path
        if not path.exists():
            raise SystemExit(f"Missing JS source file: {path}")
        body = path.read_text(encoding="utf-8")
        body = strip_leading_banner(body)
        body = trim_blank_runs(body)
        parts.append(f"/* Source: js/{rel_path} */\n{body}")

    output = (
        "/* Auto-generated by scripts/build_main_bundle.py. */\n"
        "/* Do not edit js/main.bundle.js directly; edit js/main-*.js and rebuild. */\n\n"
        + ";\n".join(parts).rstrip()
        + "\n"
    )
    OUTPUT.write_text(output, encoding="utf-8")
    size = OUTPUT.stat().st_size
    print(f"Built {OUTPUT.relative_to(ROOT)} from {len(SOURCES)} source file(s), {size} bytes.")

    if _HAS_RJSMIN:
        minified = rjsmin.jsmin(output)
        OUTPUT_MIN.write_text(minified, encoding="utf-8")
        min_size = OUTPUT_MIN.stat().st_size
        savings = round((1 - min_size / size) * 100)
        print(f"Minified {OUTPUT_MIN.relative_to(ROOT)}: {min_size} bytes ({savings}% smaller).")
    else:
        print("rjsmin not installed — skipping minification. Run: pip install rjsmin")

    return 0


if __name__ == "__main__":
    sys.exit(build())
